twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        # Récupères la variables qu'on a définie dans servicess.yaml et le transmet à toutes les vues
        locales: '%app.locales%'

when@test:
    twig:
        strict_variables: true
